//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAccount
    {
        public int Account_Number { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public string Customername { get; set; }
        public string Login_Password { get; set; }
        public string Transaction_Password { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Register_Internet_Banking { get; set; }
        public string Login_Status { get; set; }
        public Nullable<System.TimeSpan> Logout_Time { get; set; }
        public Nullable<int> Reference_Id { get; set; }
        public Nullable<int> Otp { get; set; }
        //public string Confirm_Login_Password { get; set; }
    
        public UserDetail UserDetail { get; set; }
    }
}
